site_name: libalternativa
repo_url: https://github.com/Pyogenics/libalternativa
edit_uri: tree/master/docs
docs_dir: docs

plugins:
  - search
  - git-committers:
      repository: Pyogenics/libalternativa
      branch: master

theme:
  name: bootstrap4

nav:
  - Home: index.md
  - Tanki Online:
    - A3D: formats/tanki/a3d.md
    - BattleMap: formats/tanki/battlemap.md
    - XML map: formats/tanki/xmlmap.md
    - JSON map: formats/tanki/jsonmap.md
    - LightmapData: formats/tanki/lightmapdata.md
    - Tara: formats/tanki/tara.md
  - Alternativa3D:
    - A3D: formats/alternativa3d/a3d.md
  - Other:
    - Alternativa Protocol: formats/alternativaprotocol.md
